title: Dylan Ledesma
description: All my projects, ideas and thoughts.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
github: https://www.github.com/dyylanl
linkedin: https://www.linkedin.com/in/dylan-ledesma/
twitter: https://x.com/dyylanl